version: 2

updates:
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '08:00'  # yamllint disable-line rule:quoted-strings
      timezone: America/Toronto

  # Ruby Gems
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
      time: '08:00'  # yamllint disable-line rule:quoted-strings
      timezone: America/Toronto
