# Global configuration
timezone: America/Toronto

baseurl: /
description: The website of the Swiss Club Toronto
markdown: GFM
title: Swiss Club Toronto
url: https://swissclubto.github.io

# Contact and social
email: info@swissclubtoronto.ca
twitter_username: swissclubto
github_username: swissclubto

# Build settings
theme: minima
plugins:
  - jekyll-feed
