# Global configuration
# Conversion
markdown: GFM

# Outputting
timezone: America/Toronto

# Plugins
# minima
theme: minima
header_pages:
  - contact/index.md
  - contact/officers.md
email: info@swissclubtoronto.ca
facebook_username: swissclubtoronto
github_username: swissclubto
instagram_username: swissclubto
rss: rss
twitter_username: swissclubto

# jekyll-seo-tag
title: Swiss Club Toronto
tagline: Website of the Swiss Club Toronto
description: >
  Website of the Swiss Club Toronto with information about the club, upcoming
  events, and more
url: https://swissclubto.github.io
twitter:
  username: swissclubto
  card: summary
social:
  - https://twitter.com/swissclubto
  - https://www.facebook.com/swissclubtoronto
  - https://www.linkedin.com/company/swissclubto
  - https://github.com/swissclubto
