# Plugins that aren't enabled in github-pages by default
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-sitemap
  - jemoji

# Theme: Minimal Mistakes
remote_theme: mmistakes/minimal-mistakes@4.24.0

# Skin
minimal_mistakes_skin: air

# Site locale
locale: en-CA

# Site title
title: Swiss Club Toronto
title_separator: '|'

# Name for site author
name: Swiss Club Toronto

# Site description
description: >
  Website of the Swiss Club Toronto with information about the club, upcoming
  events, and more

# Site URL
url: https://swissclubto.github.io

# Site repository
repository: swissclubto/swissclubto.github.io

# Site scripts
head_scripts:
  # Netlify CMS
  - https://identity.netlify.com/v1/netlify-identity-widget.js

# Site default teaser image
teaser: /assets/images/post-teaser.jpg

# Site masthead logo
logo: /assets/images/logo.png

# SEO and social sharing
twitter:
  username: swissclubto
facebook:
  username: swissclubto
# Open graph default image
og_image: /assets/images/logo.jpg
# Social profile information for Google Knowledge panel
social:
  type: Organization
  name: Swiss Club Toronto
  links:
    - https://www.facebook.com/swissclubtoronto
    - https://www.instagram.com/swissclubto/
    - https://twitter.com/swissclubto
    - https://www.linkedin.com/company/swissclubto/
    - https://github.com/swissclubto

# Site author

# Site footer
footer:
  links:
    - label: Facebook
      icon: fab fa-fw fa-facebook-f icon-black
      url: https://www.facebook.com/swissclubtoronto
    - label: Instagram
      icon: fab fa-fw fa-instagram icon-black
      url: https://www.instagram.com/swissclubto/
    - label: Twitter
      icon: fab fa-fw fa-twitter icon-black
      url: https://twitter.com/swissclubto
    - label: LinkedIn
      icon: fab fa-fw fa-linkedin-in icon-black
      url: https://www.linkedin.com/company/swissclubto/
    - label: GitHub
      icon: fab fa-fw fa-github icon-black
      url: https://github.com/swissclubto

# Reading files
include:
  - _pages
exclude:
  - .mailmap
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

# Outputting
permalink: pretty
timezone: America/Toronto

# Serve command options
future: true

# Collections
collections:
  events:
    output: true
    permalink: /:collection/:year/:month/:slug
  gallery:
    output: true
    permalink: /:collection/:year/:month/:slug
  officers:

# Front matter defaults
defaults:
  - scope:
      path: ''
    values:
      header:
        overlay_image: /assets/images/header.jpg
        image_description: >
          The Swiss Flag in front of the Old City Hall and high rise buildings,
          seen from City Hall
        overlay_filter: 0.2
        show_overlay_excerpt: false
  # _posts
  - scope:
      path: ''
      type: posts
    values:
      layout: single
      show_date: true
  # _pages
  - scope:
      path: ''
      type: pages
    values:
      layout: single
  # Membership pages
  - scope:
      path: _pages/membership*
    values:
      sidebar:
        nav: membership
  # _gallery
  - scope:
      path: ''
      type: gallery
    values:
      layout: gallery
      show_date: true
  # _events
  - scope:
      path: ''
      type: events
    values:
      layout: event
      show_date: true
      excerpt: ''
