# Global configuration
timezone: America/Toronto

title: Swiss Club Toronto
email: info@swissclubtoronto.ca
description: The website of the Swiss Club Toronto
twitter_username: swissclubto
github_username: swissclubto
url: https://swissclubto.github.io

# Build settings
theme: minima
plugins:
  - jekyll-feed
