title: Swiss Club Toronto
email: info@swissclubtoronto.ca
description: The website of the Swiss Club Toronto
twitter_username: swissclubto
github_username: swissclubto

# Build settings
theme: minima
plugins:
  - jekyll-feed
