source "https://rubygems.org"

ruby file: ".tool-versions"

gem "base64"
gem "csv"
gem "jekyll"
gem "jekyll-feed"
gem "jekyll-include-cache"
gem "jekyll-last-modified-at"
gem "jekyll-paginate-v2"
gem "jekyll-redirect-from"
gem "jekyll-sitemap"
gem "jemoji"
gem "logger"
gem "minimal-mistakes-jekyll", "4.24.0"
