backend:
  name: github
  repo: swissclubto/swissclubto.github.io
  branch: main
publish_mode: editorial_workflow
media_folder: /assets/pdf
logo_url: https://swissclubtoronto.ca/assets/images/logo.svg

collections:
  - name: posts
    label: News
    folder: _posts
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - label: Title
        name: title
        widget: string
      - label: Author
        name: author
        widget: string
      - label: Body
        name: body
        widget: markdown
        buttons:
          - bold
          - italic
          - code
          - link
          - heading-two
          - heading-three
          - heading-four
          - heading-five
          - heading-six
          - quote
          - bulleted-list
          - numbered-list

  - name: events
    label: Events
    label_singular: Event
    description: Posts that show up under the "Events" tab
    folder: _events
    media_folder: ../assets/images
    create: true
    delete: false
    extension: md
    format: yaml-frontmatter
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - label: Title
        name: title
        widget: string
      - label: Date
        name: date
        widget: datetime
        format: YYYY-MM-DD
        date_format: YYYY-MM-DD
        time_format: false
      - label: Location
        name: location
        widget: string
      - label: Address
        name: address
        widget: string
        required: false
      - label: Web URL
        name: web_url
        widget: string
        required: false
      - label: Web URL name
        name: web_url_name
        widget: string
        required: false
        hint: Link text for web URL
      - label: Start time
        name: start_time
        widget: datetime
        required: false
        default:
        format: h:mm a
        date_format: false
        time_format: true
      - label: End time
        name: end_time
        widget: datetime
        required: false
        default:
        format: h:mm a
        date_format: false
        time_format: true
      - label: End date
        name: end_date
        widget: datetime
        required: false
        default:
        format: YYYY-MM-DD
        date_format: YYYY-MM-DD
        time_format: false
      - label: Contacts
        name: contacts
        widget: select
        multiple: true
        options:
          - Arno
          - Ben
          - Charlotte
          - Erika
          - Heidy
          - Jean-Marc
          - Maggie
          - Nadia
          - Paula
          - Simone
          - Suzi
          - Walter
        required: false
      - label: Cost
        name: cost
        widget: text
        required: false
        hint: Put one price with description per line
      - label: Teaser
        name: teaser
        widget: image
        choose_url: false
        allow_multiple: false
        required: false
        media_folder: /assets/images
        hint: Image should be no wider than 700 pixels
      - label: Teaser caption
        name: teaser_caption
        widget: string
        required: false
      - label: Body
        required: false
        name: body
        widget: markdown
        buttons:
          - bold
          - italic
          - code
          - link
          - heading-two
          - heading-three
          - heading-four
          - heading-five
          - heading-six
          - quote
          - bulleted-list
          - numbered-list
    editor:
      preview: false
    summary: '{{year}}-{{month}}-{{day}} | {{title}}'
    view_filters:
      - label: '2023'
        field: date
        pattern: '2023'
      - label: '2022'
        field: date
        pattern: '2022'
      - label: '2021'
        field: date
        pattern: '2021'
      - label: '2020'
        field: date
        pattern: '2020'
      - label: '2019'
        field: date
        pattern: '2019'
      - label: '2018'
        field: date
        pattern: '2018'
      - label: '2017'
        field: date
        pattern: '2017'
      - label: '2016'
        field: date
        pattern: '2016'
      - label: '2015'
        field: date
        pattern: '2015'
      - label: '2014'
        field: date
        pattern: '2014'
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
