name: Add issues and PRs to project

on:
  issues:
    types:
      - opened
      - transferred
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issues and PRs
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-20.04
    steps:
      - name: Add issue or PR to new SCT website project
        uses: actions/add-to-project@v0.2.0
        with:
          project-url: https://github.com/orgs/swissclubto/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
