name: Add issues and PRs to project

on:
  issues:
    types:
      - opened
      - transferred
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issues and PRs
    uses: bewuethr/workflows/.github/workflows/addtoproject.yml@main
    with:
      project-url: https://github.com/orgs/swissclubto/projects/1
    secrets:
      github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
