name: Deploy page

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: Build page
    runs-on: ubuntu-20.04
    permissions:
      contents: read
    steps:
      - name: Check out repo
        uses: actions/checkout@v3.1.0

      - name: Setup Ruby
        # yamllint disable-line rule:line-length
        uses: ruby/setup-ruby@eae47962baca661befdfd24e4d6c34ade04858f7  # v1.118.0
        with:
          ruby-version: 2.7.4
          bundler-cache: true

      - name: Setup Pages
        uses: actions/configure-pages@v2.1.1

      - name: Build with Jekyll
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build --verbose

#     - name: Upload artifact
#       uses: actions/upload-pages-artifact@v1.0.4

# deploy:
#   name: Deploy page
#   environment:
#     name: github-pages
#     url: ${{ steps.deployment.outputs.page_url }}
#   runs-on: ubuntu-20.04
#   needs: build
#   permissions:
#     pages: write
#     id-token: write
#   steps:
#     - name: Deploy to GitHub Pages
#       id: deployment
#       uses: actions/deploy-pages@v1.2.2
