#!/usr/bin/env bash

year=$1
month=$2

date=$(date --date="$year-$month-01" +%F)

while [[ $date == *-$month-* ]]; do
	case $(date --date="$date" +%A) in
		'Monday') mondays+=("$(date --date="$date" +%F)") ;;
		'Wednesday') wednesdays+=("$(date --date="$date" +%F)") ;;
	esac

	date=$(date --date="$date + 1 day" +%F)
done

# Men's kaffi klatsch every Monday
menmonday='_events/2023-04-03-mens-kaffi-klatsch.md'

for date in "${mondays[@]}"; do
	target="_events/$date-mens-kaffi-klatsch$((++i)).md"
	cp "$menmonday" "$target"
	date="$date" yq --inplace --front-matter=process \
		'.date = env(date)' "$target"
done

# Men's virtual kaffi klatsch on the third Wednesday
menvirtual='_events/2023-04-19-mens-virtual-klatsch.md'
target="_events/${mondays[2]}-mens-virtual-klatsch.md"
cp "$menvirtual" "$target"
date="${mondays[2]}" yq --inplace --front-matter=process \
	'.date = env(date)' "$target"

# Women's klatsch on the first Wednesday
womensfirst='_events/2023-04-05-womens-kaffeeklatsch.md'
target="_events/${wednesdays[0]}-womens-kaffeeklatsch1.md"
cp "$womensfirst" "$target"
date="${wednesdays[0]}" yq --inplace --front-matter=process \
	'.date = env(date)' "$target"

# Women's klatsch on the last Wednesday
womenslast='_events/2023-04-26-womens-kaffeeklatsch2.md'
target="_events/${wednesdays[-1]}-womens-kaffeeklatsch2.md"
cp "$womenslast" "$target"
date="${wednesdays[-1]}" yq --inplace --front-matter=process \
	'.date = env(date)' "$target"
